//
//  BigUInt.swift
//  privamesh
//
//  Minimal fixed-purpose arbitrary-precision UNSIGNED integer, just enough for
//  the client side of the RSA blind-signature token protocol (see
//  BlindTokenService): big-endian bytes <-> integer, multiply, divmod, modular
//  exponentiation, and modular inverse. Base 2^32 limbs, little-endian.
//
//  NOT constant-time and NOT a general bignum library. It is used only for the
//  client's blinding maths, whose SECRECY (unlinkability) is information-
//  theoretic in the random blinding factor and does not rest on timing. Do not
//  reuse this for secret-key operations that need side-channel resistance.
//
//  Correctness is covered by test/BigUIntTests.swift (run with the `swift`
//  CLI against vectors generated by the relay's node test).
//

import Foundation

struct BigUInt: Comparable, Equatable {
    /// Little-endian base-2^32 limbs, no trailing zero limbs (except value 0 == []).
    private(set) var limbs: [UInt32]

    // MARK: init

    init() { limbs = [] }

    init(_ value: UInt32) { limbs = value == 0 ? [] : [value] }

    init(limbs: [UInt32]) {
        self.limbs = limbs
        normalize()
    }

    /// Big-endian bytes → integer.
    init(bytes: [UInt8]) {
        var l: [UInt32] = []
        var i = bytes.count
        while i > 0 {
            var limb: UInt32 = 0
            var shift: UInt32 = 0
            var taken = 0
            while taken < 4 && i > 0 {
                i -= 1
                limb |= UInt32(bytes[i]) << shift
                shift += 8
                taken += 1
            }
            l.append(limb)
        }
        limbs = l
        normalize()
    }

    /// Big-endian bytes, left-padded/truncated to exactly `count` bytes.
    /// Traps if the value does not fit — callers pad to the modulus width.
    func toBytes(count: Int) -> [UInt8] {
        var out = [UInt8](repeating: 0, count: count)
        for i in 0..<limbs.count {
            let limb = limbs[i]
            for b in 0..<4 {
                let byteVal = UInt8((limb >> (UInt32(b) * 8)) & 0xff)
                let pos = count - 1 - (i * 4 + b)
                if byteVal != 0 && pos < 0 {
                    fatalError("BigUInt.toBytes: value wider than \(count) bytes")
                }
                if pos >= 0 { out[pos] = byteVal }
            }
        }
        return out
    }

    private mutating func normalize() {
        while let last = limbs.last, last == 0 { limbs.removeLast() }
    }

    var isZero: Bool { limbs.isEmpty }

    // MARK: compare

    static func < (a: BigUInt, b: BigUInt) -> Bool { a.compare(b) < 0 }
    static func == (a: BigUInt, b: BigUInt) -> Bool { a.limbs == b.limbs }

    /// -1 if self<other, 0 if equal, 1 if self>other.
    func compare(_ other: BigUInt) -> Int {
        if limbs.count != other.limbs.count {
            return limbs.count < other.limbs.count ? -1 : 1
        }
        var i = limbs.count - 1
        while i >= 0 {
            if limbs[i] != other.limbs[i] {
                return limbs[i] < other.limbs[i] ? -1 : 1
            }
            i -= 1
        }
        return 0
    }

    // MARK: add / sub

    static func + (a: BigUInt, b: BigUInt) -> BigUInt {
        var out: [UInt32] = []
        let n = max(a.limbs.count, b.limbs.count)
        var carry: UInt64 = 0
        for i in 0..<n {
            let av = i < a.limbs.count ? UInt64(a.limbs[i]) : 0
            let bv = i < b.limbs.count ? UInt64(b.limbs[i]) : 0
            let sum = av + bv + carry
            out.append(UInt32(sum & 0xffff_ffff))
            carry = sum >> 32
        }
        if carry != 0 { out.append(UInt32(carry)) }
        return BigUInt(limbs: out)
    }

    /// self - other, requires self >= other.
    static func - (a: BigUInt, b: BigUInt) -> BigUInt {
        var out: [UInt32] = []
        var borrow: Int64 = 0
        for i in 0..<a.limbs.count {
            let av = Int64(a.limbs[i])
            let bv = i < b.limbs.count ? Int64(b.limbs[i]) : 0
            var diff = av - bv - borrow
            if diff < 0 { diff += 0x1_0000_0000; borrow = 1 } else { borrow = 0 }
            out.append(UInt32(diff))
        }
        return BigUInt(limbs: out)
    }

    // MARK: multiply

    static func * (a: BigUInt, b: BigUInt) -> BigUInt {
        if a.isZero || b.isZero { return BigUInt() }
        var out = [UInt64](repeating: 0, count: a.limbs.count + b.limbs.count)
        for i in 0..<a.limbs.count {
            var carry: UInt64 = 0
            let av = UInt64(a.limbs[i])
            for j in 0..<b.limbs.count {
                let cur = out[i + j] + av * UInt64(b.limbs[j]) + carry
                out[i + j] = cur & 0xffff_ffff
                carry = cur >> 32
            }
            out[i + b.limbs.count] += carry
        }
        return BigUInt(limbs: out.map { UInt32($0 & 0xffff_ffff) })
    }

    // MARK: bit helpers

    var bitWidth: Int {
        guard let top = limbs.last else { return 0 }
        return (limbs.count - 1) * 32 + (32 - top.leadingZeroBitCount)
    }

    func bit(_ i: Int) -> Bool {
        let limb = i / 32, off = i % 32
        if limb >= limbs.count { return false }
        return (limbs[limb] >> UInt32(off)) & 1 == 1
    }

    /// self << 1
    func shiftedLeft1() -> BigUInt {
        var out: [UInt32] = []
        var carry: UInt32 = 0
        for limb in limbs {
            out.append((limb << 1) | carry)
            carry = limb >> 31
        }
        if carry != 0 { out.append(carry) }
        return BigUInt(limbs: out)
    }

    // MARK: divmod (bitwise long division)

    /// Returns (quotient, remainder) for self / divisor. Traps on divide-by-zero.
    func divMod(_ divisor: BigUInt) -> (q: BigUInt, r: BigUInt) {
        precondition(!divisor.isZero, "division by zero")
        if compare(divisor) < 0 { return (BigUInt(), self) }
        var q = BigUInt()
        var r = BigUInt()
        var i = bitWidth - 1
        while i >= 0 {
            r = r.shiftedLeft1()
            if bit(i) {
                // set low bit of r
                if r.limbs.isEmpty { r = BigUInt(1) }
                else { r.limbs[0] |= 1 }
            }
            if r.compare(divisor) >= 0 {
                r = r - divisor
                q.setBit(i)
            }
            i -= 1
        }
        q.normalize(); r.normalize()
        return (q, r)
    }

    private mutating func setBit(_ i: Int) {
        let limb = i / 32, off = i % 32
        while limbs.count <= limb { limbs.append(0) }
        limbs[limb] |= (UInt32(1) << UInt32(off))
    }

    func mod(_ m: BigUInt) -> BigUInt { divMod(m).r }

    // MARK: modular ops

    func mulMod(_ other: BigUInt, _ m: BigUInt) -> BigUInt {
        (self * other).mod(m)
    }

    /// self^exp mod m (square-and-multiply).
    func powMod(_ exp: BigUInt, _ m: BigUInt) -> BigUInt {
        if m == BigUInt(1) { return BigUInt() }
        var result = BigUInt(1)
        var base = mod(m)
        let width = exp.bitWidth
        var i = 0
        while i < width {
            if exp.bit(i) { result = result.mulMod(base, m) }
            base = base.mulMod(base, m)
            i += 1
        }
        return result
    }

    /// Modular inverse self^-1 mod m via the iterative extended Euclid, kept fully
    /// unsigned by reducing the Bézout coefficient mod m at each step. Returns nil
    /// if self is not invertible mod m (gcd != 1).
    func inverseMod(_ m: BigUInt) -> BigUInt? {
        if m == BigUInt(1) { return BigUInt() }
        var t = BigUInt()            // coefficient, in [0, m)
        var newt = BigUInt(1)
        var r = m
        var newr = mod(m)
        while !newr.isZero {
            let (q, rem) = r.divMod(newr)
            // (t, newt) = (newt, t - q*newt)  — computed mod m, unsigned
            let qn = q.mulMod(newt, m)
            let tSub = (t.compare(qn) >= 0) ? (t - qn) : (m - (qn - t))
            t = newt
            newt = tSub.mod(m)
            // (r, newr) = (newr, r - q*newr) = (newr, rem)
            r = newr
            newr = rem
        }
        if r.compare(BigUInt(1)) > 0 { return nil }   // gcd > 1, not invertible
        return t
    }
}
